// Package status contains status definitions for the TDX verification package.
package status

// Status describes the TCB status of a TDX platform
type Status uint32

// List of possible status code values of the Quote Verification Library functions.
// Status codes indicate the result of an operation.
// See: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/32b80caa1815fd00801d42d1ff8cbf82784ca21b/QuoteVerification/QVL/Src/AttestationLibrary/include/SgxEcdsaAttestation/QuoteVerification.h
const (
	OK Status = iota // 0
	UNSUPPORTED_CERT_FORMAT
	SGX_ROOT_CA_MISSING
	SGX_ROOT_CA_INVALID
	SGX_ROOT_CA_INVALID_EXTENSIONS
	SGX_ROOT_CA_INVALID_ISSUER
	SGX_ROOT_CA_UNTRUSTED
	SGX_INTERMEDIATE_CA_MISSING
	SGX_INTERMEDIATE_CA_INVALID
	SGX_INTERMEDIATE_CA_INVALID_EXTENSIONS
	SGX_INTERMEDIATE_CA_INVALID_ISSUER // 10
	SGX_INTERMEDIATE_CA_REVOKED
	SGX_PCK_MISSING
	SGX_PCK_INVALID
	SGX_PCK_INVALID_EXTENSIONS
	SGX_PCK_INVALID_ISSUER
	SGX_PCK_REVOKED
	TRUSTED_ROOT_CA_INVALID
	SGX_PCK_CERT_CHAIN_UNTRUSTED
	SGX_TCB_INFO_UNSUPPORTED_FORMAT
	SGX_TCB_INFO_INVALID // 20
	TCB_INFO_INVALID_SIGNATURE
	SGX_TCB_SIGNING_CERT_MISSING
	SGX_TCB_SIGNING_CERT_INVALID
	SGX_TCB_SIGNING_CERT_INVALID_EXTENSIONS
	SGX_TCB_SIGNING_CERT_INVALID_ISSUER
	SGX_TCB_SIGNING_CERT_CHAIN_UNTRUSTED
	SGX_TCB_SIGNING_CERT_REVOKED
	SGX_CRL_UNSUPPORTED_FORMAT
	SGX_CRL_UNKNOWN_ISSUER
	SGX_CRL_INVALID // 30
	SGX_CRL_INVALID_EXTENSIONS
	SGX_CRL_INVALID_SIGNATURE
	SGX_CA_CERT_UNSUPPORTED_FORMAT
	SGX_CA_CERT_INVALID
	TRUSTED_ROOT_CA_UNSUPPORTED_FORMAT
	MISSING_PARAMETERS
	UNSUPPORTED_QUOTE_FORMAT
	UNSUPPORTED_PCK_CERT_FORMAT
	INVALID_PCK_CERT
	UNSUPPORTED_PCK_RL_FORMAT // 40
	INVALID_PCK_CRL
	UNSUPPORTED_TCB_INFO_FORMAT
	PCK_REVOKED
	TCB_INFO_MISMATCH
	TCB_OUT_OF_DATE
	TCB_REVOKED
	TCB_CONFIGURATION_NEEDED
	TCB_OUT_OF_DATE_CONFIGURATION_NEEDED
	TCB_NOT_SUPPORTED
	TCB_UNRECOGNIZED_STATUS // 50
	UNSUPPORTED_QE_CERTIFICATION
	INVALID_QE_CERTIFICATION_DATA_SIZE
	UNSUPPORTED_QE_CERTIFICATION_DATA_TYPE
	PCK_CERT_MISMATCH
	INVALID_QE_REPORT_SIGNATURE
	INVALID_QE_REPORT_DATA
	INVALID_QUOTE_SIGNATURE
	SGX_QE_IDENTITY_UNSUPPORTED_FORMAT
	SGX_QE_IDENTITY_INVALID
	SGX_QE_IDENTITY_INVALID_SIGNATURE // 60
	SGX_ENCLAVE_REPORT_UNSUPPORTED_FORMAT
	SGX_ENCLAVE_IDENTITY_UNSUPPORTED_FORMAT
	SGX_ENCLAVE_IDENTITY_INVALID
	SGX_ENCLAVE_IDENTITY_UNSUPPORTED_VERSION
	SGX_ENCLAVE_IDENTITY_OUT_OF_DATE
	SGX_ENCLAVE_REPORT_MISCSELECT_MISMATCH
	SGX_ENCLAVE_REPORT_ATTRIBUTES_MISMATCH
	SGX_ENCLAVE_REPORT_MRENCLAVE_MISMATCH
	SGX_ENCLAVE_REPORT_MRSIGNER_MISMATCH
	SGX_ENCLAVE_REPORT_ISVPRODID_MISMATCH // 70
	SGX_ENCLAVE_REPORT_ISVSVN_OUT_OF_DATE
	UNSUPPORTED_QE_IDENTITY_FORMAT
	QE_IDENTITY_OUT_OF_DATE
	QE_IDENTITY_MISMATCH
	SGX_TCB_INFO_EXPIRED
	SGX_ENCLAVE_IDENTITY_INVALID_SIGNATURE
	INVALID_PARAMETER
	SGX_PCK_CERT_CHAIN_EXPIRED
	SGX_CRL_EXPIRED
	SGX_SIGNING_CERT_CHAIN_EXPIRED // 80
	SGX_ENCLAVE_IDENTITY_EXPIRED
	TCB_SW_HARDENING_NEEDED
	TCB_CONFIGURATION_AND_SW_HARDENING_NEEDED
	SGX_ENCLAVE_REPORT_ISVSVN_REVOKED
	TDX_MODULE_MISMATCH
)

type TCBStatus string

const (
	UpToDate                          TCBStatus = "UpToDate"
	ConfigurationNeeded               TCBStatus = "ConfigurationNeeded"
	OutOfDate                         TCBStatus = "OutOfDate"
	OutOfDateConfigurationNeeded      TCBStatus = "OutOfDateConfigurationNeeded"
	ConfigurationAndSWHardeningNeeded TCBStatus = "ConfigurationAndSWHardeningNeeded"
	SWHardeningNeeded                 TCBStatus = "SWHardeningNeeded"
	Revoked                           TCBStatus = "Revoked"
)

// ConvergeTCBStatus returns the converged TCB status of a TDX platform.
func ConvergeTCBStatus(tcbLevelStatus, qeIdentityStatus Status) Status {
	if qeIdentityStatus == SGX_ENCLAVE_REPORT_ISVSVN_OUT_OF_DATE {
		if tcbLevelStatus == OK ||
			tcbLevelStatus == TCB_SW_HARDENING_NEEDED {
			return TCB_OUT_OF_DATE
		}
		if tcbLevelStatus == TCB_CONFIGURATION_NEEDED ||
			tcbLevelStatus == TCB_CONFIGURATION_AND_SW_HARDENING_NEEDED {
			return TCB_OUT_OF_DATE_CONFIGURATION_NEEDED
		}
	}

	if qeIdentityStatus == SGX_ENCLAVE_REPORT_ISVSVN_REVOKED {
		return TCB_REVOKED
	}

	switch tcbLevelStatus {
	case TCB_OUT_OF_DATE,
		TCB_REVOKED,
		TCB_CONFIGURATION_NEEDED,
		TCB_OUT_OF_DATE_CONFIGURATION_NEEDED,
		TCB_SW_HARDENING_NEEDED,
		TCB_CONFIGURATION_AND_SW_HARDENING_NEEDED,
		OK:
		return tcbLevelStatus
	default:
		// 4.1.2.4.16.4
		return TCB_UNRECOGNIZED_STATUS
	}
}
