// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: qgs.message.proto

package tdxproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qgs_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_qgs_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_qgs_message_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*Request_GetQuoteRequest_
	Msg isRequest_Msg `protobuf_oneof:"msg"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qgs_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_qgs_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_qgs_message_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (m *Request) GetMsg() isRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Request) GetGetQuoteRequest() *Request_GetQuoteRequest {
	if x, ok := x.GetMsg().(*Request_GetQuoteRequest_); ok {
		return x.GetQuoteRequest
	}
	return nil
}

type isRequest_Msg interface {
	isRequest_Msg()
}

type Request_GetQuoteRequest_ struct {
	GetQuoteRequest *Request_GetQuoteRequest `protobuf:"bytes,2,opt,name=getQuoteRequest,oneof"`
}

func (*Request_GetQuoteRequest_) isRequest_Msg() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*Response_GetQuoteResponse_
	Msg isResponse_Msg `protobuf_oneof:"msg"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qgs_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_qgs_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_qgs_message_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (m *Response) GetMsg() isResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Response) GetGetQuoteResponse() *Response_GetQuoteResponse {
	if x, ok := x.GetMsg().(*Response_GetQuoteResponse_); ok {
		return x.GetQuoteResponse
	}
	return nil
}

type isResponse_Msg interface {
	isResponse_Msg()
}

type Response_GetQuoteResponse_ struct {
	GetQuoteResponse *Response_GetQuoteResponse `protobuf:"bytes,2,opt,name=getQuoteResponse,oneof"`
}

func (*Response_GetQuoteResponse_) isResponse_Msg() {}

type Request_GetQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report []byte  `protobuf:"bytes,1,req,name=report" json:"report,omitempty"`
	IdList []*UUID `protobuf:"bytes,2,rep,name=id_list,json=idList" json:"id_list,omitempty"`
}

func (x *Request_GetQuoteRequest) Reset() {
	*x = Request_GetQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qgs_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_GetQuoteRequest) ProtoMessage() {}

func (x *Request_GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qgs_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*Request_GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_qgs_message_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Request_GetQuoteRequest) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *Request_GetQuoteRequest) GetIdList() []*UUID {
	if x != nil {
		return x.IdList
	}
	return nil
}

type Response_GetQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode  *uint32 `protobuf:"varint,1,req,name=error_code,json=errorCode,def=1" json:"error_code,omitempty"`
	SelectedId *UUID   `protobuf:"bytes,2,opt,name=selected_id,json=selectedId" json:"selected_id,omitempty"`
	Quote      []byte  `protobuf:"bytes,3,opt,name=quote" json:"quote,omitempty"`
}

// Default values for Response_GetQuoteResponse fields.
const (
	Default_Response_GetQuoteResponse_ErrorCode = uint32(1)
)

func (x *Response_GetQuoteResponse) Reset() {
	*x = Response_GetQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qgs_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_GetQuoteResponse) ProtoMessage() {}

func (x *Response_GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qgs_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*Response_GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_qgs_message_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Response_GetQuoteResponse) GetErrorCode() uint32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return Default_Response_GetQuoteResponse_ErrorCode
}

func (x *Response_GetQuoteResponse) GetSelectedId() *UUID {
	if x != nil {
		return x.SelectedId
	}
	return nil
}

func (x *Response_GetQuoteResponse) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_qgs_message_proto protoreflect.FileDescriptor

var file_qgs_message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x67, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x71, 0x67, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xcd,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x50,
	0x0a, 0x0f, 0x67, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x71, 0x67, 0x73, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0f, 0x67, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x55, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x69,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71,
	0x67, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xfb,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x54, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x71, 0x67, 0x73, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x7e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x3a, 0x01, 0x31,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x71, 0x67, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x52, 0x0a, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x0e, 0x48, 0x03,
	0x5a, 0x0a, 0x2e, 0x2f, 0x74, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_qgs_message_proto_rawDescOnce sync.Once
	file_qgs_message_proto_rawDescData = file_qgs_message_proto_rawDesc
)

func file_qgs_message_proto_rawDescGZIP() []byte {
	file_qgs_message_proto_rawDescOnce.Do(func() {
		file_qgs_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_qgs_message_proto_rawDescData)
	})
	return file_qgs_message_proto_rawDescData
}

var file_qgs_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_qgs_message_proto_goTypes = []interface{}{
	(*UUID)(nil),                      // 0: qgs.message.UUID
	(*Request)(nil),                   // 1: qgs.message.Request
	(*Response)(nil),                  // 2: qgs.message.Response
	(*Request_GetQuoteRequest)(nil),   // 3: qgs.message.Request.GetQuoteRequest
	(*Response_GetQuoteResponse)(nil), // 4: qgs.message.Response.GetQuoteResponse
}
var file_qgs_message_proto_depIdxs = []int32{
	3, // 0: qgs.message.Request.getQuoteRequest:type_name -> qgs.message.Request.GetQuoteRequest
	4, // 1: qgs.message.Response.getQuoteResponse:type_name -> qgs.message.Response.GetQuoteResponse
	0, // 2: qgs.message.Request.GetQuoteRequest.id_list:type_name -> qgs.message.UUID
	0, // 3: qgs.message.Response.GetQuoteResponse.selected_id:type_name -> qgs.message.UUID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_qgs_message_proto_init() }
func file_qgs_message_proto_init() {
	if File_qgs_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qgs_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qgs_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qgs_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qgs_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_GetQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qgs_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_GetQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_qgs_message_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Request_GetQuoteRequest_)(nil),
	}
	file_qgs_message_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Response_GetQuoteResponse_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qgs_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qgs_message_proto_goTypes,
		DependencyIndexes: file_qgs_message_proto_depIdxs,
		MessageInfos:      file_qgs_message_proto_msgTypes,
	}.Build()
	File_qgs_message_proto = out.File
	file_qgs_message_proto_rawDesc = nil
	file_qgs_message_proto_goTypes = nil
	file_qgs_message_proto_depIdxs = nil
}
